### ISSUE TITLE
Parceria

### ISSUE THREAD

**Issue by marcosgerene** [adrianotrentim/bancobr-net#1]
Bom dia,

Tenho demanda para ITAU.

O que precisa para acelerar o desenvolvimento? (grana/codigo/oração...)

**Comment by orochasamuel** [comment]
@marcosgerene um pouco de tudo hahahaha

Tem mais de 1 ano que o @adrianotrentim falou comigo a respeito desse projeto e de lá para cá a luta foi tamanha que não consegui contribuir.

Vou iniciar em breve a implementação do Santander, tenho 3 clientes carentes.

Anyway, qualquer colaboração/contribuição é sempre bem vinda.

Vida longa e próspera 🖖

**Comment by marcosgerene** [comment]
@orochasamuel falaaaa

Falei com ele hoje via meetings, o Itau que preciso ta indo para homologação.

Vou tentar vender o Sicoob aqui e ai implemento.

Um abraço

**Comment by adrianotrentim** [comment]
Qualquer colaboração é bem vinda, Itaú vai abrir homologação semana que vem, Bradesco em produção..... falamos em meet, assim que eu homologar Itaú dou um ok.
